// <auto-generated />
using System;
using AICT.SIMS.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AICT.SIMS.Persistence.Migrations
{
    [DbContext(typeof(DatabaseService))]
    partial class DatabaseServiceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Entities", b =>
                {
                    b.Property<int>("Entityid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entityid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Entityid"));

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Entityname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entityname");

                    b.Property<int?>("Parententityid")
                        .HasColumnType("integer")
                        .HasColumnName("parententityid");

                    b.HasKey("Entityid");

                    b.HasIndex("Parententityid");

                    b.ToTable("entities");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Imagerequests", b =>
                {
                    b.Property<Guid>("Requestid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("requestid");

                    b.Property<decimal?>("Completionpercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("completionpercentage");

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("Createdbyuserid")
                        .HasColumnType("integer")
                        .HasColumnName("createdbyuserid");

                    b.Property<string>("Feasibilitydetails")
                        .HasColumnType("jsonb")
                        .HasColumnName("feasibilitydetails");

                    b.Property<int>("Mainentityid")
                        .HasColumnType("integer")
                        .HasColumnName("mainentityid");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Requestformfilename")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("requestformfilename");

                    b.Property<byte[]>("Requestformimage")
                        .HasColumnType("bytea")
                        .HasColumnName("requestformimage");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int>("Subentityid")
                        .HasColumnType("integer")
                        .HasColumnName("subentityid");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Requestid");

                    b.HasIndex("Createdbyuserid");

                    b.HasIndex("Mainentityid");

                    b.HasIndex("Subentityid");

                    b.HasIndex(new[] { "Status" }, "idx_req_status");

                    b.ToTable("imagerequests");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Operationslog", b =>
                {
                    b.Property<long>("Logid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("logid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Logid"));

                    b.Property<string>("Actiontaken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actiontaken");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<DateTime?>("Logtimestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("logtimestamp");

                    b.Property<int?>("Performedbyuserid")
                        .HasColumnType("integer")
                        .HasColumnName("performedbyuserid");

                    b.Property<Guid>("Requestid")
                        .HasColumnType("uuid")
                        .HasColumnName("requestid");

                    b.HasKey("Logid");

                    b.HasIndex("Performedbyuserid");

                    b.HasIndex("Requestid");

                    b.ToTable("operationslog");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Requestassignments", b =>
                {
                    b.Property<int>("Assignmentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assignmentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Assignmentid"));

                    b.Property<DateTime?>("Assignedat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assignedat");

                    b.Property<int?>("Assignedbyuserid")
                        .HasColumnType("integer")
                        .HasColumnName("assignedbyuserid");

                    b.Property<Guid>("Requestid")
                        .HasColumnType("uuid")
                        .HasColumnName("requestid");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Assignmentid");

                    b.HasIndex("Assignedbyuserid");

                    b.HasIndex("Userid");

                    b.HasIndex(new[] { "Requestid", "Userid" }, "requestassignments_requestid_userid_key")
                        .IsUnique();

                    b.ToTable("requestassignments");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Requesttargets", b =>
                {
                    b.Property<int>("Targetid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("targetid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Targetid"));

                    b.Property<DateTime?>("Capturedate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("capturedate");

                    b.Property<bool?>("Iscaptured")
                        .HasColumnType("boolean")
                        .HasColumnName("iscaptured");

                    b.Property<Guid>("Requestid")
                        .HasColumnType("uuid")
                        .HasColumnName("requestid");

                    b.Property<Geometry>("Targetgeometry")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry,4326)")
                        .HasColumnName("targetgeometry");

                    b.Property<string>("Targetlabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("targetlabel");

                    b.HasKey("Targetid");

                    b.HasIndex("Requestid");

                    b.ToTable("requesttargets");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Roles", b =>
                {
                    b.Property<int>("Roleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Roleid"));

                    b.Property<string>("Rolename")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rolename");

                    b.HasKey("Roleid");

                    b.HasIndex(new[] { "Rolename" }, "roles_rolename_key")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Satellites", b =>
                {
                    b.Property<int>("Satelliteid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("satelliteid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Satelliteid"));

                    b.Property<DateTime?>("Lastupdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastupdate");

                    b.Property<int?>("Noradid")
                        .HasColumnType("integer")
                        .HasColumnName("noradid");

                    b.Property<string>("Satellitename")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("satellitename");

                    b.Property<double>("Swathwidthkm")
                        .HasColumnType("double precision")
                        .HasColumnName("swathwidthkm");

                    b.Property<string>("Tleline1")
                        .HasColumnType("text")
                        .HasColumnName("tleline1");

                    b.Property<string>("Tleline2")
                        .HasColumnType("text")
                        .HasColumnName("tleline2");

                    b.HasKey("Satelliteid");

                    b.HasIndex(new[] { "Noradid" }, "satellites_noradid_key")
                        .IsUnique();

                    b.ToTable("satellites");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.SysParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ParamValue")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("SysParam");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Users", b =>
                {
                    b.Property<int>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Userid"));

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fullname");

                    b.Property<bool?>("Isactive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool?>("Isadmin")
                        .HasColumnType("boolean")
                        .HasColumnName("isadmin");

                    b.Property<int?>("Parentuserid")
                        .HasColumnType("integer")
                        .HasColumnName("parentuserid");

                    b.Property<int?>("Roleid")
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    b.HasKey("Userid");

                    b.HasIndex("Parentuserid");

                    b.HasIndex("Roleid");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Entities", b =>
                {
                    b.HasOne("AICT.SIMS.Domain.DomainEntities.Entities", "Parententity")
                        .WithMany("InverseParententity")
                        .HasForeignKey("Parententityid");

                    b.Navigation("Parententity");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Imagerequests", b =>
                {
                    b.HasOne("AICT.SIMS.Domain.DomainEntities.Users", "Createdbyuser")
                        .WithMany("Imagerequests")
                        .HasForeignKey("Createdbyuserid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AICT.SIMS.Domain.DomainEntities.Entities", "Mainentity")
                        .WithMany("ImagerequestsMainentity")
                        .HasForeignKey("Mainentityid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AICT.SIMS.Domain.DomainEntities.Entities", "Subentity")
                        .WithMany("ImagerequestsSubentity")
                        .HasForeignKey("Subentityid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Createdbyuser");

                    b.Navigation("Mainentity");

                    b.Navigation("Subentity");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Operationslog", b =>
                {
                    b.HasOne("AICT.SIMS.Domain.DomainEntities.Users", "Performedbyuser")
                        .WithMany("Operationslog")
                        .HasForeignKey("Performedbyuserid");

                    b.HasOne("AICT.SIMS.Domain.DomainEntities.Imagerequests", "Request")
                        .WithMany("Operationslog")
                        .HasForeignKey("Requestid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performedbyuser");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Requestassignments", b =>
                {
                    b.HasOne("AICT.SIMS.Domain.DomainEntities.Users", "Assignedbyuser")
                        .WithMany("RequestassignmentsAssignedbyuser")
                        .HasForeignKey("Assignedbyuserid");

                    b.HasOne("AICT.SIMS.Domain.DomainEntities.Imagerequests", "Request")
                        .WithMany("Requestassignments")
                        .HasForeignKey("Requestid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AICT.SIMS.Domain.DomainEntities.Users", "User")
                        .WithMany("RequestassignmentsUser")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignedbyuser");

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Requesttargets", b =>
                {
                    b.HasOne("AICT.SIMS.Domain.DomainEntities.Imagerequests", "Request")
                        .WithMany("Requesttargets")
                        .HasForeignKey("Requestid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Users", b =>
                {
                    b.HasOne("AICT.SIMS.Domain.DomainEntities.Users", "Parentuser")
                        .WithMany("InverseParentuser")
                        .HasForeignKey("Parentuserid");

                    b.HasOne("AICT.SIMS.Domain.DomainEntities.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("Roleid");

                    b.Navigation("Parentuser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Entities", b =>
                {
                    b.Navigation("ImagerequestsMainentity");

                    b.Navigation("ImagerequestsSubentity");

                    b.Navigation("InverseParententity");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Imagerequests", b =>
                {
                    b.Navigation("Operationslog");

                    b.Navigation("Requestassignments");

                    b.Navigation("Requesttargets");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AICT.SIMS.Domain.DomainEntities.Users", b =>
                {
                    b.Navigation("Imagerequests");

                    b.Navigation("InverseParentuser");

                    b.Navigation("Operationslog");

                    b.Navigation("RequestassignmentsAssignedbyuser");

                    b.Navigation("RequestassignmentsUser");
                });
#pragma warning restore 612, 618
        }
    }
}
